services:
  frontend:
    restart: always
    build:
      context: frontend/.
    ports:
      - "8010:8010"
    environment:
      - NODE_ENV=production
    command: sh -c "npm run build && npm install -g serve && serve -s dist -l 8010"
  
  backend:
    restart: always
    build:
      context: backend/.
    ports:
      - "8011:8000"
    env_file: ".env"
    command: uv run uvicorn main:app --host 0.0.0.0 --port 8000
