x-app_environment: &app_env
  environment:
    # Backend
    - BITRIX_WEBHOOK
    - DEFAULT_USER
    # Frontend
    - VITE_API_URL
    - VITE_BASE_PATH
    - NODE_ENV


services:
  frontend:
    restart: always
    build:
      context: frontend/.
    ports: 
    - "8010:8010"
    <<: *app_env
    command: sh -c "npm run build && npm install -g serve && serve -s dist -l 8010"
  
  backend:
    restart: always
    build:
      context: backend/.
    ports: 
    - "8011:8000"
    <<: *app_env
    command: uv run uvicorn main:app --host 0.0.0.0 --port 8000
